### ISSUE TITLE
Update Snowplow Mini to use external schema registry

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-mini#89] opened 2017-04-13 23:23 UTC
This is part of the *making Snowplow Mini stateless* initiative.

The rationale for having stateless Snowplow Mini is that it should make upgrades much easier, and make data loss less likely.

**Comment by alexanderdean** [comment] 2017-07-14 09:03
This is covered I believe by the existing Control Plane API ticket around Iglu resolver...

**Comment by aldemirenes** [comment] 2017-07-14 09:45
Yes, this issue is duplicate of the [this ticket](https://github.com/snowplow/snowplow-mini/issues/62), closing

**Closed by aldemirenes** 2017-07-14 09:45 UTC
